In [1]:
import torch

In [2]:
torch.__version__

'2.3.0+cu121'

A single number is scalar in torch with dimension equals to 0.

In [3]:
#scalar
t1 = torch.tensor(1)
print('scalar t1: ', t1)
print('t1.ndim(): ',t1.ndim)
print('t1.item(): ',t1.item())

scalar t1:  tensor(1)
t1.ndim():  0
t1.item():  1


In [4]:
#vector
t2 = torch.tensor([1,2])
print('vector t2: ',t2)
print('t2.ndim: ', t2.ndim)
print('t2.shape: ', t2.shape)
# .item() is used for single value retrieval only
print('t2[0].item(): ', t2[0].item())


vector t2:  tensor([1, 2])
t2.ndim:  1
t2.shape:  torch.Size([2])
t2[0].item():  1


In [5]:
#matrix

T3 = torch.tensor([[1,2],[3,4]])
print('matrix T3: \n', T3)

matrix T3: 
 tensor([[1, 2],
        [3, 4]])


In [6]:
print('T3.shape: ',T3.shape)
print('T3.ndim: ', T3.ndim)

T3.shape:  torch.Size([2, 2])
T3.ndim:  2


In practice, you'll often see scalars and vectors denoted as lowercase letters such as y or a. And matrices and tensors denoted as uppercase letters such as X or W.

In [7]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.dtype)

tensor([[0.5276, 0.8248, 0.6846, 0.5120],
        [0.9566, 0.6348, 0.7865, 0.2712],
        [0.4845, 0.3951, 0.0515, 0.4798]])
torch.float32


In [8]:
random_image_tensor = torch.rand(size=(224,224,3))
print(random_image_tensor)

tensor([[[0.7628, 0.6723, 0.5929],
         [0.6718, 0.9217, 0.3290],
         [0.1752, 0.5805, 0.3247],
         ...,
         [0.7247, 0.5144, 0.6877],
         [0.2884, 0.7944, 0.9584],
         [0.8767, 0.4606, 0.7684]],

        [[0.7677, 0.7884, 0.5566],
         [0.0201, 0.7761, 0.0115],
         [0.0757, 0.4230, 0.8204],
         ...,
         [0.6565, 0.5923, 0.1714],
         [0.4706, 0.7387, 0.0052],
         [0.3370, 0.1510, 0.9860]],

        [[0.7168, 0.4490, 0.9374],
         [0.0493, 0.9386, 0.8171],
         [0.3961, 0.3049, 0.4552],
         ...,
         [0.5328, 0.9379, 0.3507],
         [0.1055, 0.8140, 0.4142],
         [0.5447, 0.8184, 0.2756]],

        ...,

        [[0.7677, 0.5555, 0.3397],
         [0.7369, 0.5130, 0.8108],
         [0.9261, 0.6497, 0.3772],
         ...,
         [0.1039, 0.2763, 0.4544],
         [0.0511, 0.2314, 0.8079],
         [0.3131, 0.2480, 0.3559]],

        [[0.4226, 0.0615, 0.6634],
         [0.6891, 0.1445, 0.2582],
         [0.

In [9]:
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([224, 224, 3]))

In [10]:
#zero tensor

zeros = torch.zeros(size=(2,3))
zeros,zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [11]:
#ones tensor
ones = torch.ones(size=(2,3))
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [12]:
# ranged tensor [start,end)
ranged_tensor = torch.arange(start=2, end=10, step=1)
ranged_tensor

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
torch.arange(start=3, end=15, step=3)

tensor([ 3,  6,  9, 12])

In [14]:
# Sometimes you might want one tensor of a certain type with the same shape as another tensor.

zero_like = torch.zeros_like(input = ranged_tensor )
zero_like

tensor([0, 0, 0, 0, 0, 0, 0, 0])

#### Torch Tensor Datatypes
Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).



In [15]:
# Default datatype for tensors is float32

f32_tensor = torch.tensor([1.0,2.3, 4.5],
                          dtype=None, #default float32
                          device=None, #default cpu
                          requires_grad=False)# Default datatype for tensors is float32
print(f32_tensor.shape,'--', f32_tensor.dtype,'--', f32_tensor.device)
f32_tensor

torch.Size([3]) -- torch.float32 -- cpu


tensor([1.0000, 2.3000, 4.5000])

In [16]:
f16 = torch.tensor([1.0,2.3,4.5], dtype=torch.float16)
f16

tensor([1.0000, 2.3008, 4.5000], dtype=torch.float16)

General errors in pytorch include one of the three errors

- tensor shape
- tensor datatype
- tensor device

#### Basic Operation

In [17]:
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])


In [18]:
torch.multiply(tensor, 5)

tensor([ 5, 10, 15])

In [19]:
#element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [20]:
# matrix multiplication
#method 1
print(tensor.matmul(tensor))
# method 2
print(tensor @ tensor)

tensor(14)
tensor(14)


In [21]:
a = torch.tensor([[1,2],[3,4]])
torch.matmul(a,a)

tensor([[ 7, 10],
        [15, 22]])

In [22]:
# also
torch.mm(a,a)

tensor([[ 7, 10],
        [15, 22]])

#### Linear Layers

In [23]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, # number of columns in input matrix/ matches inner dimension of input
                         out_features=8 # number of columns in output matrix/ describes outer value
                         )
linear

Linear(in_features=2, out_features=8, bias=True)

In [24]:
f32_tensor = torch.tensor([[1,2],
                           [3,4],
                           [4,5]],dtype=torch.float32)

In [25]:
f32_tensor.dtype

torch.float32

In [26]:
output = linear(f32_tensor)
output

tensor([[ 2.2595,  1.2380, -0.1997,  0.6665, -0.7400,  0.7964,  0.4267,  0.6104],
        [ 4.5145,  2.2058, -0.2241,  0.8086, -0.5308,  2.2903,  1.6631,  1.0926],
        [ 5.6421,  2.6897, -0.2364,  0.8796, -0.4262,  3.0372,  2.2813,  1.3337]],
       grad_fn=<AddmmBackward0>)

In [27]:
output.shape

torch.Size([3, 8])

In [28]:
print(output.min())
print(output.argmin()) #index of minimum value

tensor(-0.7400, grad_fn=<MinBackward1>)
tensor(4)


In [29]:
print(output.max())
print(output.argmax()) #index of max value

tensor(5.6421, grad_fn=<MaxBackward1>)
tensor(16)


In [30]:
output.mean()

tensor(1.3366, grad_fn=<MeanBackward0>)

In [31]:
output.sum()

tensor(32.0788, grad_fn=<SumBackward0>)

In [32]:
output.dtype

torch.float32

In [33]:
output16 = output.type(torch.float16)
output16

tensor([[ 2.2598,  1.2383, -0.1997,  0.6665, -0.7397,  0.7964,  0.4268,  0.6104],
        [ 4.5156,  2.2051, -0.2241,  0.8086, -0.5308,  2.2910,  1.6631,  1.0928],
        [ 5.6406,  2.6895, -0.2363,  0.8794, -0.4263,  3.0371,  2.2812,  1.3340]],
       dtype=torch.float16, grad_fn=<ToCopyBackward0>)

In [34]:
# Returns a view of the original tensor in a different shape
#  but shares the same data as the original tensor.
output16.view((12,2)) #done before reshape

tensor([[ 2.2598,  1.2383],
        [-0.1997,  0.6665],
        [-0.7397,  0.7964],
        [ 0.4268,  0.6104],
        [ 4.5156,  2.2051],
        [-0.2241,  0.8086],
        [-0.5308,  2.2910],
        [ 1.6631,  1.0928],
        [ 5.6406,  2.6895],
        [-0.2363,  0.8794],
        [-0.4263,  3.0371],
        [ 2.2812,  1.3340]], dtype=torch.float16, grad_fn=<ViewBackward0>)

In [35]:
# Concatenates a sequence of tensors along
# a new dimension (dim), all tensors must be same size.
torch.stack((output,output),dim=0)

tensor([[[ 2.2595,  1.2380, -0.1997,  0.6665, -0.7400,  0.7964,  0.4267,
           0.6104],
         [ 4.5145,  2.2058, -0.2241,  0.8086, -0.5308,  2.2903,  1.6631,
           1.0926],
         [ 5.6421,  2.6897, -0.2364,  0.8796, -0.4262,  3.0372,  2.2813,
           1.3337]],

        [[ 2.2595,  1.2380, -0.1997,  0.6665, -0.7400,  0.7964,  0.4267,
           0.6104],
         [ 4.5145,  2.2058, -0.2241,  0.8086, -0.5308,  2.2903,  1.6631,
           1.0926],
         [ 5.6421,  2.6897, -0.2364,  0.8796, -0.4262,  3.0372,  2.2813,
           1.3337]]], grad_fn=<StackBackward0>)

In [36]:
torch.stack((output,output),dim=1)

tensor([[[ 2.2595,  1.2380, -0.1997,  0.6665, -0.7400,  0.7964,  0.4267,
           0.6104],
         [ 2.2595,  1.2380, -0.1997,  0.6665, -0.7400,  0.7964,  0.4267,
           0.6104]],

        [[ 4.5145,  2.2058, -0.2241,  0.8086, -0.5308,  2.2903,  1.6631,
           1.0926],
         [ 4.5145,  2.2058, -0.2241,  0.8086, -0.5308,  2.2903,  1.6631,
           1.0926]],

        [[ 5.6421,  2.6897, -0.2364,  0.8796, -0.4262,  3.0372,  2.2813,
           1.3337],
         [ 5.6421,  2.6897, -0.2364,  0.8796, -0.4262,  3.0372,  2.2813,
           1.3337]]], grad_fn=<StackBackward0>)

In [37]:
torch.stack((output,output),dim=2)

tensor([[[ 2.2595,  2.2595],
         [ 1.2380,  1.2380],
         [-0.1997, -0.1997],
         [ 0.6665,  0.6665],
         [-0.7400, -0.7400],
         [ 0.7964,  0.7964],
         [ 0.4267,  0.4267],
         [ 0.6104,  0.6104]],

        [[ 4.5145,  4.5145],
         [ 2.2058,  2.2058],
         [-0.2241, -0.2241],
         [ 0.8086,  0.8086],
         [-0.5308, -0.5308],
         [ 2.2903,  2.2903],
         [ 1.6631,  1.6631],
         [ 1.0926,  1.0926]],

        [[ 5.6421,  5.6421],
         [ 2.6897,  2.6897],
         [-0.2364, -0.2364],
         [ 0.8796,  0.8796],
         [-0.4262, -0.4262],
         [ 3.0372,  3.0372],
         [ 2.2813,  2.2813],
         [ 1.3337,  1.3337]]], grad_fn=<StackBackward0>)

In [38]:
output_int = output.type(torch.int8)
output_int

tensor([[2, 1, 0, 0, 0, 0, 0, 0],
        [4, 2, 0, 0, 0, 2, 1, 1],
        [5, 2, 0, 0, 0, 3, 2, 1]], dtype=torch.int8)

In [39]:
# Squeezes input to remove all the dimenions with value 1.
x = torch.ones(2,1,2,1)
print(x)
y = torch.squeeze(x)
#If the tensor has a batch dimension of size 1,
# then squeeze(input) will also remove the batch dimension,
#  which can lead to unexpected errors. Consider specifying
# only the dims you wish to be squeezed.
print(y)

tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])
tensor([[1., 1.],
        [1., 1.]])


In [40]:
torch.unsqueeze(x,dim=0)#	Returns input with a dimension value of 1 added at dim.
# A dim value within the range [-input.dim() - 1, input.dim() + 1) can be used.
# Negative dim will correspond to unsqueeze() applied at dim = dim + input.dim() + 1.

tensor([[[[[1.],
           [1.]]],


         [[[1.],
           [1.]]]]])

In [41]:
print("a:" ,a)
b = torch.tensor([[4,5],[6,7]])
print("b:", b)
print()
c = torch.stack([a,b])
c

a: tensor([[1, 2],
        [3, 4]])
b: tensor([[4, 5],
        [6, 7]])



tensor([[[1, 2],
         [3, 4]],

        [[4, 5],
         [6, 7]]])

In [42]:
# Returns a view of the original input with its dimensions permuted (rearranged) to dims.
# dims (tuple of int) – The desired ordering of dimensions

torch.permute(a,dims=[1,0]) # shifts axis 0->1, 1->0

tensor([[1, 3],
        [2, 4]])

In [43]:
c.shape

torch.Size([2, 2, 2])

In [44]:
torch.permute(c,dims=[1,0,2])

tensor([[[1, 2],
         [4, 5]],

        [[3, 4],
         [6, 7]]])

#### Indexing

In [45]:
c[:]

tensor([[[1, 2],
         [3, 4]],

        [[4, 5],
         [6, 7]]])

In [46]:
c[1]

tensor([[4, 5],
        [6, 7]])

In [47]:
c[0,0]

tensor([1, 2])