In [1]:
import torch
import numpy as np


#### Pytorch and Numpy

By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

In [6]:
np_array = np.arange(1.0,8.0)
np_array

array([1., 2., 3., 4., 5., 6., 7.])

In [7]:
tensor = torch.from_numpy(np_array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [8]:
#  to convert from tensor to numpy
tensor.numpy(), tensor.numpy().dtype

(array([1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))

#### Seed and Random State

Reproducibility: To keep the randomly initialized values same, seed is fixed at some random state

In [9]:
import random

torch.manual_seed(seed=42)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

#### GPU Computations

In [10]:
torch.cuda.is_available()

True

In [11]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [12]:
torch.cuda.device_count()

1

In [16]:
random_tensor, random_tensor.device

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 device(type='cpu'))

In [17]:
gpu_tensor = random_tensor.to(device)
gpu_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]], device='cuda:0')

In [18]:
# moving tensor back to cpu
# tensor on gpu cannot be directly converted to numpy as numpy arrays work on cpu
gpu_tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [19]:
gpu_tensor.cpu().numpy()

array([[0.88226926, 0.91500396, 0.38286376, 0.95930564],
       [0.3904482 , 0.60089535, 0.25657248, 0.7936413 ],
       [0.94077146, 0.13318592, 0.9345981 , 0.59357965]], dtype=float32)